add subsection
OpenDevUFCG/portal pull request #8
Opened 2023-10-25 00:49 UTC by laysasantos2

- [x] Minha contribuição respeita o [código de conduta](https://github.com/OpenDevUFCG/Tamburetei/blob/master/CODE_OF_CONDUCT.md) do repositório.
- [x] Minha contribuição respeita as [restrições de upload](https://github.com/OpenDevUFCG/Tamburetei/wiki/Restrições-de-Upload) do repositório.

2023-10-25 23:02 UTC, jessescn requested changes

2023-10-25 23:02 UTC, jessescn commented on src/components/SubSection.tsx
Alterar a organização do arquivo para o seguinte:

1. Criar uma pasta dentro de /components com o nome SubSection
2. No lugar de SubSection.tsx, criar um arquivo index.tsx dentro de /SubSection
3. No lugar de SubSection.css, criar um arquivo subsection.module.css dentro de /SubSection e ajustar o import para o novo nome

2023-10-26 00:35 UTC, RodrigoEC commented on src/components/SubSection/subsection.module.css
> +    font-size: 36px;
Acredito que esse título pode ser um pouquinho menor

```suggestion
    font-size: 32px;
```

2023-10-26 00:38 UTC, RodrigoEC commented on src/components/SubSection/subsection.module.css
> +    font-size: 20px;
Esse também poderia ser menorzinho

```suggestion
    font-size: 18px;
```

2023-10-26 00:38 UTC, RodrigoEC commented on src/components/SubSection/subsection.module.css
> +    line-height: 1rem;
```suggestion
    line-height: 1.5rem;
```

2023-10-26 00:39 UTC, RodrigoEC requested changes
Muito bom!! Pedi só umas alteraçõezinhas alem do que @jessescn pediu, umas coisas de estilo da página mesmo

2023-10-26 21:25 UTC, jessescn approved these changes

2023-10-27 02:09 UTC, merged